[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "QDWSATZ-NUB05286"
user = "FAEEZKANA"
password = "7VyY2RZ!01PB%*vCS%lj"
